version: "3.8"
services:
  client:
    image: client-dev-i
    build:
      dockerfile: Dockerfile.dev
    container_name: client-dev-c
    ports:
      - "5173:5173"
    volumes:
      - ./client:/client
      - node_modules:/client/node_modules/
volumes:
  node_modules:
